# NumPy

Tutorial para aprender a trabajar con `arrays` de NumPy en Python.

In [1]:
import numpy as np

El objetivo de NumPy es trabajar con arrays multidimensionales, que pueden pensarse como una tabla de elementos (normalmente números) del mismo tipo indexados por una tupla de enteros no-negativos. 

De manera análoga a la función `range` de Python, podemos crear un array con números enteros entre 0 y 10:

In [2]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


Si usamos el método `size` obtenemos la cantidad de elementos

In [3]:
arr.size

10

con `dtype` podemos conocer el tipo de dato que almacena (entero, flotante, etc)

In [4]:
arr.dtype

dtype('int64')

de hecho a la hora de crearlo podemos especificarlo

In [5]:
arr = np.arange(10, dtype=np.float64)
arr

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

(notar que ahora muestra los valores con sus decimales (0))

## Crear un Array

`arange` no es la única forma de hacerlo, podemos crear un arreglo a partir de una lista de Python

In [6]:
np.array([1.2, 9.1, 0.25])

array([1.2 , 9.1 , 0.25])

donde el tipo de dato se deduce de lo que contenga la lista. También se pueden crear arrays que tengan todos sus elementos inicializados en cero

In [7]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

o unos

In [8]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

por efecto los define como flotantes. Además de `arange` está la función `linspace` para controlar la cantidad de valores equiespaciados en cierto rango

In [9]:
np.linspace(0, 2, num=9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

esto es util, por ejemplo, para evaluar función

In [10]:
x = np.linspace(0, 2 * np.pi, num=9)
np.cos(x)

array([ 1.00000000e+00,  7.07106781e-01,  6.12323400e-17, -7.07106781e-01,
       -1.00000000e+00, -7.07106781e-01, -1.83697020e-16,  7.07106781e-01,
        1.00000000e+00])

## Operaciones básicas

las operaciones matemáticas básicas que teníamos para números, se aplican a los arrays elemento-a-elemento

In [11]:
np.array([1, 2, 3]) + np.ones(3)

array([2., 3., 4.])

si esto quisieramos hacerlo con listas no sería tan directo, es decir, si sumamos listas no tendríamos el mismo resultado que al sumar arrays

In [12]:
[1, 2, 3] + [1, 1, 1]

[1, 2, 3, 1, 1, 1]

para ello tenemos que hacer un loop

In [13]:
l1 = [1, 2, 3]
l2 = [1, 1, 1]
ltot = []
for i in range(len(l1)):
    ltot.append(l1[i] + l2[i])
print(ltot)

[2, 3, 4]


también es posible multiplicar arrays por un escalar

In [14]:
2 * np.array([1, 2, 3])

array([2, 4, 6])

mientras que con las listas nos las concatena dos veces

In [15]:
2 * [1, 2, 3]

[1, 2, 3, 1, 2, 3]

entonces nuevamente habría que hacer un for loop

In [16]:
l = [1, 2, 3]
for i in range(len(l)):
    l[i] = 2 * l[i]
print(l)

[2, 4, 6]


o elevar a algún numéro

In [17]:
np.array([1, 2, 3])**2

array([1, 4, 9])

o multiplicar dos arrays

In [18]:
np.array([1, 2, 3]) * np.array([1, 2, 3])

array([1, 4, 9])

nuevamente, con las listas habría que iterar.

Dado un array podemos calcular la suma de todos sus elementos (como con la función `sum` de Python, pero solo que en NumPy)

In [19]:
x = np.linspace(0, 2 * np.pi, num=9)
arr = np.cos(x)
np.sum(arr)

0.9999999999999996

encontrar el mínimo

In [20]:
np.min(arr)

-1.0

o el máximo

In [21]:
np.max(arr)

1.0

también podemos acceder a algún valor en particular, al primero

In [22]:
arr[0]

1.0

al penúltimo

In [23]:
arr[-2]

0.7071067811865474

desde el tercero, los 4 siguientes

In [24]:
arr[2:6]

array([ 6.12323400e-17, -7.07106781e-01, -1.00000000e+00, -7.07106781e-01])

## Fuente

https://numpy.org/doc/stable/user/quickstart.html