# NumPy

Tutorial para aprender a trabajar con `arrays` de NumPy en Python.

In [1]:
import numpy as np

El objetivo de NumPy es trabajar con arrays multidimensionales, que pueden pensarse como una tabla de elementos (normalmente números) del mismo tipo indexados por una tupla de enteros no-negativos. A las dimensiones en NumPy se las llama `axes`. De manera análoga a la función `range` de Python, podemos crear un array con números enteros entre 0 y 10:

In [2]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

y cambiarle su forma con el método `reshape(filas, columnas)`.

In [3]:
arr = np.arange(10).reshape(2, 5)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

ahora este array tiene 2 filas y 5 columnas. Si usamos el método `size` obtenemos la cantidad de elementos (filas * columnas)

In [4]:
arr.size

10

con `dtype` podemos conocer el tipo de dato que almacena (entero, flotante, etc)

In [5]:
arr.dtype

dtype('int64')

de hecho a la hora de crearlo podemos especificarlo

In [6]:
arr = np.arange(10, dtype=np.float64).reshape(2, 5)
arr

array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.]])

(notar que ahora muestra los valores con sus decimales (0))

## Crear un Array

`arange` no es la única forma de hacerlo, podemos crear un arreglo a partir de una lista de Python

In [7]:
np.array([1.2, 9.1, 0.25])

array([1.2 , 9.1 , 0.25])

o a partir de una tupla

In [8]:
np.array((1.2, 9.1, 0.25))

array([1.2 , 9.1 , 0.25])

donde el tipo de dato se deduce de lo que contenga la lista o la tupla. También se pueden crear arrays que tengan todos sus elementos inicializados en cero

In [9]:
np.zeros((2, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

o unos

In [10]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

por efecto los define como flotantes. Además de `arange` está la función `linspace` para controlar la cantidad de valores equiespaciados en cierto rango

In [11]:
np.linspace(0, 2, num=17)

array([0.   , 0.125, 0.25 , 0.375, 0.5  , 0.625, 0.75 , 0.875, 1.   ,
       1.125, 1.25 , 1.375, 1.5  , 1.625, 1.75 , 1.875, 2.   ])

esto es util para evaluar función (que teníamos definidas en `math` pero que también están en NumPy)

In [12]:
x = np.linspace(0, 2 * np.pi, num=17)
np.cos(x)

array([ 1.00000000e+00,  9.23879533e-01,  7.07106781e-01,  3.82683432e-01,
        6.12323400e-17, -3.82683432e-01, -7.07106781e-01, -9.23879533e-01,
       -1.00000000e+00, -9.23879533e-01, -7.07106781e-01, -3.82683432e-01,
       -1.83697020e-16,  3.82683432e-01,  7.07106781e-01,  9.23879533e-01,
        1.00000000e+00])

## Operaciones básicas

las operaciones matemáticas básicas que teníamos para números, se aplican a los arrays elemento-a-elemento

In [13]:
np.array([1, 2, 3]) + np.ones(3)

array([2., 3., 4.])

también es posible multiplicar arrays por un escalar

In [14]:
2 * np.array([1, 2, 3])

array([2, 4, 6])

o elevar a algún numéro

In [15]:
np.array([1, 2, 3])**2

array([1, 4, 9])

In [16]:
np.array([1, 2, 3]) * np.array([1, 2, 3])

array([1, 4, 9])

dado un array podemos calcular la suma de todos sus elementos

In [17]:
x = np.linspace(0, 2 * np.pi, num=17)
arr = np.cos(x)
arr.sum()

0.9999999999999992

encontrar el mínimo

In [18]:
arr.min()

-1.0

o el máximo

In [19]:
arr.max()

1.0

también podemos acceder a algún valor en particular, al primero

In [20]:
arr[0]

1.0

al penúltimo

In [21]:
arr[-2]

0.9238795325112864

desde el tercero, los 4 siguientes

In [22]:
arr[2:6]

array([ 7.07106781e-01,  3.82683432e-01,  6.12323400e-17, -3.82683432e-01])

podemos iterar sobre las filas de un array, volvamos al anterior

In [23]:
arr = np.arange(20).reshape(4, 5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [24]:
for fila in arr:
    print(fila)

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]
[15 16 17 18 19]


si queremos operar sobre cada uno de los elementos, usamos el método `flat` del array multidimensional

In [25]:
for elemento in arr.flat:
    print(elemento)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


## Operaciones menos básicas

si tenemos dos arreglos se pueden concatenar

In [26]:
np.concatenate((np.arange(10), np.arange(10, -1, -1)))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10,  9,  8,  7,  6,  5,  4,
        3,  2,  1,  0])

y también se pueden dividir

In [27]:
np.split(np.arange(10), 2)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

indexar un array por otro

In [28]:
arr = np.arange(10)**2
i = [2, 4]
arr[i]

array([ 4, 16])

esto es útil cuando queremos que cumplan cierta condicion, por ejemplo tenemos los cuadrados en `arr` y solo queremos los que vienen de elevar al cuadrado un número par, entonces

In [29]:
mask = np.arange(10) % 2 == 0
mask

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [30]:
arr[mask]

array([ 0,  4, 16, 36, 64])

## Fuente

https://numpy.org/doc/stable/user/quickstart.html